In [1]:
import torch

In [4]:
# tensor, with a lower case t
# it can only accept 1 argument 
# it is to create a tensor with pre-existing data
x = torch.tensor(2)

print(x)

tensor(2)


In [6]:
# Tensor, with a capital T, creates a matrix with dimensions a*b
# Tensors are respresented using the torch.Tensor class. Because torch.Tensor is class.
# This is to represent either all the weights or all the activations from a single layer of neurons
x = torch.Tensor(5,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [17]:
print(x.dtype)
print(x.device)
print(x.layout)

torch.float32
cpu
torch.strided


In [8]:
# zeros, creates a matrix of dimensions a*b with only zeros inside
x = torch.zeros(5,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [11]:
# shape returns the dimensions of a matrix, it doesn't need to be called as a function
x.shape

torch.Size([5, 2])

In [14]:
# rand creates a matrix with random floats inside, I believe between 0 and 1
# most likely since they have to be probabilities
y = torch.rand(5,2)
print(y)

tensor([[0.2058, 0.8207],
        [0.5611, 0.5505],
        [0.2190, 0.6679],
        [0.4865, 0.8122],
        [0.8196, 0.8193]])


In [18]:
# view allows us to view a tensor array in a different set of dimenstions
y.view([10,1])

tensor([[0.2058],
        [0.8207],
        [0.5611],
        [0.5505],
        [0.2190],
        [0.6679],
        [0.4865],
        [0.8122],
        [0.8196],
        [0.8193]])

In [19]:
y.view([1,10])

tensor([[0.2058, 0.8207, 0.5611, 0.5505, 0.2190, 0.6679, 0.4865, 0.8122, 0.8196,
         0.8193]])