In [17]:
import torch

x= torch.Tensor(5,1)
y= torch.Tensor(5,2)

print(x)
print(y)
print(y*x)

tensor([[0.0000e+00],
        [0.0000e+00],
        [2.6193e+20],
        [3.3830e+21],
        [1.6971e-07]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
x = torch.zeros(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x.shape

torch.Size([5, 3])

In [6]:
y = torch.rand(2,5)
print(y)

tensor([[0.5848, 0.2013, 0.7532, 0.8947, 0.3945],
        [0.0036, 0.0031, 0.3932, 0.5104, 0.7414]])


In [8]:
y.view([1,10])

tensor([[0.5848, 0.2013, 0.7532, 0.8947, 0.3945, 0.0036, 0.0031, 0.3932, 0.5104,
         0.7414]])

In [18]:
y = y.view([1,10])

In [19]:
print(y)

tensor([[0.5955, 0.8333, 0.1878, 0.0223, 0.0970, 0.6675, 0.9152, 0.4915, 0.1566,
         0.2283]])
